from .admin import (
    admin_checklist_create,
    admin_checklist_edit,
    admin_checklist_pdf,
    admin_checklist_view,
    admin_checklists,
    admin_dashboard,
    admin_departments,
    admin_master_create,
    admin_master_create_legacy,
    admin_department_action,
    admin_checklist_action,
    admin_project_action,
    admin_projects,
    admin_response_action,
    admin_responses,
    admin_logs,
    admin_user_action,
    admin_users,
)
from .auth import home, user_login, user_logout
from .management import management_dashboard
from .user_panel import dashboard, my_checklists, my_submissions, profile, user_checklist_preview

__all__ = [
    'home',
    'user_login',
    'user_logout',
    'admin_dashboard',
    'admin_users',
    'admin_departments',
    'admin_projects',
    'admin_checklists',
    'admin_checklist_create',
    'admin_checklist_edit',
    'admin_checklist_view',
    'admin_checklist_pdf',
    'admin_responses',
    'admin_logs',
    'admin_master_create',
    'admin_master_create_legacy',
    'admin_department_action',
    'admin_checklist_action',
    'admin_project_action',
    'admin_user_action',
    'admin_response_action',
    'my_checklists',
    'my_submissions',
    'dashboard',
    'profile',
    'user_checklist_preview',
    'management_dashboard',
]
