from .admin import (
    admin_checklists,
    admin_dashboard,
    admin_departments,
    admin_master_create,
    admin_master_create_legacy,
    admin_department_action,
    admin_checklist_action,
    admin_project_action,
    admin_projects,
    admin_response_action,
    admin_responses,
    admin_user_action,
    admin_users,
)
from .auth import home, user_login, user_logout
from .user_panel import dashboard, my_checklists, my_submissions, profile

__all__ = [
    'home',
    'user_login',
    'user_logout',
    'admin_dashboard',
    'admin_users',
    'admin_departments',
    'admin_projects',
    'admin_checklists',
    'admin_responses',
    'admin_master_create',
    'admin_master_create_legacy',
    'admin_department_action',
    'admin_checklist_action',
    'admin_project_action',
    'admin_user_action',
    'admin_response_action',
    'my_checklists',
    'my_submissions',
    'dashboard',
    'profile',
]
