# Generated by Django 5.2.5 on 2026-05-05 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rolepermission_selected_projects'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='checklistresponse',
            new_name='backend_che_status_1379ce_idx',
            old_name='backend_che_status_42a098_idx',
        ),
        migrations.RenameIndex(
            model_name='checklistresponse',
            new_name='backend_che_submitt_b57879_idx',
            old_name='backend_che_submitt_e7ce4d_idx',
        ),
        migrations.RenameIndex(
            model_name='checklistresponse',
            new_name='backend_che_project_582762_idx',
            old_name='backend_che_project_db0d4c_idx',
        ),
        migrations.RenameIndex(
            model_name='checklistresponse',
            new_name='backend_che_submitt_c25aec_idx',
            old_name='backend_che_submitt_92ec81_idx',
        ),
    ]
