# Generated by Django 5.2.5 on 2026-05-06 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_expand_checklist_question_types'),
        ('backend', '0005_rename_backend_che_status_42a098_idx_backend_che_status_1379ce_idx_and_more'),
    ]

    operations = [
    ]
