# Generated by Django 5.2.5 on 2026-05-19 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_userprofile_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='checklisttransaction',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='checklisttransaction',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='checklisttransaction',
            name='department',
        ),
        migrations.RemoveField(
            model_name='checklisttransaction',
            name='last_updated_by',
        ),
        migrations.RemoveField(
            model_name='checklisttransaction',
            name='project',
        ),
        migrations.RemoveField(
            model_name='checklisttransaction',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'id']},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='is_mandatory',
            new_name='required',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='text',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='backend_act_module__7b3ddb_idx',
            old_name='backend_act_module__d1a7fa_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='backend_act_user_id_0fa4fe_idx',
            old_name='backend_act_user_id_2ab793_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='backend_act_departm_75f18d_idx',
            old_name='backend_act_departm_239609_idx',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='checklist_type',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='code',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='department',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='project',
        ),
        migrations.RemoveField(
            model_name='question',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='question',
            name='code',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('short_text', 'Short Text'), ('long_text', 'Long Text'), ('multiple_choice', 'Multiple Choice'), ('checkbox', 'Checkbox'), ('dropdown', 'Dropdown'), ('file_upload', 'File Upload'), ('yes_no', 'Yes / No'), ('date', 'Date')], default='text', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='section',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='backend.checklist'),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='backend.section'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='ChecklistTransaction',
        ),
    ]
