# Generated by Django 5.2.5 on 2026-06-10 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_assigned_hod(apps, schema_editor):
    UserProfile = apps.get_model('backend', 'UserProfile')
    profiles = UserProfile.objects.filter(assigned_hod__isnull=True).exclude(role='HOD')
    for profile in profiles:
        if not profile.department_id:
            continue
        hod_profile = (
            UserProfile.objects
            .filter(
                role='HOD',
                is_active=True,
                user__is_active=True,
                department_id=profile.department_id,
            )
            .order_by('id')
            .first()
        )
        if hod_profile:
            profile.assigned_hod_id = hod_profile.user_id
            profile.save(update_fields=['assigned_hod'])


def clear_assigned_hod(apps, schema_editor):
    UserProfile = apps.get_model('backend', 'UserProfile')
    UserProfile.objects.update(assigned_hod=None)


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_checklistresponse_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_hod',
            field=models.ForeignKey(blank=True, help_text='Primary HOD responsible for approving this user checklist responses.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_user_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(populate_assigned_hod, clear_assigned_hod),
    ]
