# Generated by Django 5.2.5 on 2026-06-11 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_responsedecision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsedecision',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='backend.checklistresponse'),
        ),
    ]
