# Generated by Django 5.2.5 on 2026-06-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_protect_response_decision_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistresponse',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklistresponse',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='checklistresponse',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='checklistresponse',
            name='submission_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
