# Generated by Django 5.2.5 on 2026-06-11 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_checklistresponse_geolocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_notifications', models.BooleanField(default=True)),
                ('enable_bell', models.BooleanField(default=True)),
                ('enable_popups', models.BooleanField(default=True)),
                ('enable_sound', models.BooleanField(default=False)),
                ('retention_days', models.PositiveIntegerField(default=365)),
                ('low_color', models.CharField(default='#6B7280', max_length=7)),
                ('medium_color', models.CharField(default='#2563EB', max_length=7)),
                ('high_color', models.CharField(default='#EA580C', max_length=7)),
                ('critical_color', models.CharField(default='#DC2626', max_length=7)),
                ('event_settings', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_setting_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(db_index=True, max_length=80)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], db_index=True, default='Medium', max_length=16)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_required', models.BooleanField(db_index=True, default=False)),
                ('related_type', models.CharField(blank=True, default='', max_length=80)),
                ('related_id', models.CharField(blank=True, default='', max_length=64)),
                ('related_url', models.CharField(blank=True, default='', max_length=500)),
                ('popup_shown_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='backend_not_recipie_8cf68a_idx'), models.Index(fields=['recipient', 'action_required', 'created_at'], name='backend_not_recipie_ec7571_idx')],
            },
        ),
    ]
