# Generated by Django 5.2.5 on 2026-06-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_appsettings_web_app_name_notificationsetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='event_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='severity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], db_index=True, default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='source',
            field=models.CharField(choices=[('UI', 'UI'), ('Admin', 'Admin'), ('System', 'System'), ('Script', 'Script'), ('API', 'API')], db_index=True, default='UI', max_length=20),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='target_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='target_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['event_key', 'timestamp'], name='backend_act_event_k_7b5ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['target_type', 'target_id'], name='backend_act_target__cd868a_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['severity', 'timestamp'], name='backend_act_severit_4d97a2_idx'),
        ),
    ]
