# Generated by Django 5.2.5 on 2026-06-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_activitylog_event_key_activitylog_severity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='web_app_name',
            field=models.CharField(default='QCMS', max_length=120),
        ),
    ]
